# Generated by Django 4.0 on 2023-10-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='associated_domain',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
