# Generated by Django 4.0 on 2023-12-11 16:01

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesBusinessInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=14, unique=True)),
                ('years_of_experience', models.CharField(max_length=15)),
                ('about', models.TextField(max_length=100)),
                ('business_photograph', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.customuser')),
            ],
        ),
    ]
