# Generated by Django 4.0 on 2023-12-14 02:31

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesbusinessinformation',
            name='business_photograph2',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to=''),
        ),
        migrations.AddField(
            model_name='servicesbusinessinformation',
            name='business_photograph3',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to=''),
        ),
    ]
