# Generated by Django 4.0 on 2023-12-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('mall', '0002_servicesbusinessinformation_business_photograph2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesbusinessinformation',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicescategory'),
        ),
    ]
