# Generated by Django 4.0 on 2023-10-15 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_store_associated_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.product')),
                ('user', models.ForeignKey(limit_choices_to={'is_consumer': True}, on_delete=django.db.models.deletion.CASCADE, to='mall.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.product')),
                ('user', models.ForeignKey(limit_choices_to={'is_consumer': True}, on_delete=django.db.models.deletion.CASCADE, to='mall.customuser')),
            ],
        ),
    ]
