# Generated by Django 4.0 on 2023-12-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_servicesbusinessinformation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesbusinessinformation',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='servicesbusinessinformation',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
