# Generated by Django 4.0 on 2023-09-06 16:07

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion
import mall.validator


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_customuser_uid_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='associated_domain',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('TIN_number', models.IntegerField()),
                ('logo', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to='')),
                ('year_of_establishment', models.DateField(validators=[mall.validator.YearValidator])),
                ('domain_name', models.CharField(max_length=100, unique=True)),
                ('store_url', models.URLField(unique=True)),
                ('owner', models.OneToOneField(limit_choices_to={'is_store_owner': True}, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='mall.customuser')),
            ],
        ),
    ]
