# Generated by Django 4.0 on 2023-09-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_customuser_associated_domain_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_consumer',
            field=models.BooleanField(default=False),
        ),
    ]
