# Generated by Django 4.0 on 2023-10-15 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_alter_store_tin_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='mall.Product')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mall.store')),
            ],
        ),
    ]
