# Generated by Django 4.0 on 2023-12-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('mall', '0004_servicesbusinessinformation_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesbusinessinformation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicescategory'),
        ),
    ]
