# Generated by Django 4.0 on 2023-10-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_marketplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='listed',
            field=models.BooleanField(default=False),
        ),
    ]
