# Generated by Django 4.0 on 2023-09-06 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_customuser_is_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='associated_domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.store'),
        ),
    ]
