# Generated by Django 4.0 on 2024-01-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_reportuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportuser',
            name='support_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
