# Generated by Django 4.0 on 2023-10-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_marketplace_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='list_product',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='listed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
