# Generated by Django 4.0 on 2023-09-06 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_category_subcategories_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mall.category'),
        ),
    ]
