# Generated by Django 4.0 on 2024-01-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_reportuser_support_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportuser',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In-Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=11),
        ),
    ]
