# Generated by Django 4.0 on 2023-10-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_product_list_product_alter_marketplace_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ManyToManyField(to='mall.Store'),
        ),
        migrations.DeleteModel(
            name='MarketPlace',
        ),
    ]
