# Generated by Django 4.0 on 2023-09-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0008_alter_brand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
