# Generated by Django 4.0 on 2024-01-13 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0008_reportuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproductpricing',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='storeproductpricing',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varied_products', to='mall.productvariant'),
        ),
    ]
