# Generated by Django 4.0 on 2023-10-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0008_product_store_delete_marketplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='mall.Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.store')),
            ],
        ),
    ]
