# Generated by Django 4.0 on 2023-09-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0009_alter_subcategories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
