# Generated by Django 4.0 on 2024-01-13 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0009_remove_storeproductpricing_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductpricing',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varied_products', to='mall.product'),
        ),
    ]
