# Generated by Django 4.0 on 2023-10-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0009_marketplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplace',
            name='product',
        ),
        migrations.AddField(
            model_name='marketplace',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.product'),
        ),
    ]
