# Generated by Django 4.0 on 2023-09-07 09:28

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0010_alter_subcategories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.fields.CharField, related_name='subcategories', to='mall.category'),
        ),
    ]
