# Generated by Django 4.0 on 2024-01-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0010_alter_storeproductpricing_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportuser',
            name='title',
            field=models.CharField(choices=[('Inappropriate Behavior', 'Inappropriate Behavior'), ('Violating Terms of Service', 'Violating Terms of Service'), ('Shipping and Fulfillment Issues', 'Shipping and Fulfillment Issues'), ('Poor Customer Service', 'Poor Customer Service'), ('Unfair Competition Practices', 'Unfair Competition Practices'), ('Fraudulent Activities', 'Fraudulent Activities'), ('Others', 'Others')], max_length=31, null=True),
        ),
    ]
