# Generated by Django 4.0 on 2023-10-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0010_remove_marketplace_product_marketplace_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='list_product',
            field=models.BooleanField(default=False),
        ),
    ]
