# Generated by Django 4.0 on 2023-09-07 15:16

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0011_alter_subcategories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='cover_image',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to=''),
        ),
    ]
