# Generated by Django 4.0 on 2023-10-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0012_remove_product_list_product_marketplace_list_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='list_product',
            field=models.BooleanField(default=True),
        ),
    ]
