# Generated by Django 4.0 on 2023-09-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0015_alter_customuser_managers_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
