# Generated by Django 4.0 on 2023-10-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0015_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.producttypes'),
        ),
    ]
