# Generated by Django 4.0 on 2023-09-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0016_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
