# Generated by Django 4.0 on 2023-10-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0016_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='producttype',
        ),
    ]
