# Generated by Django 4.0 on 2024-02-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0017_alter_store_domain_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='temp_id',
        ),
    ]
