# Generated by Django 4.0 on 2023-09-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0017_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='uid_idx',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='uid',
            new_name='id',
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['id'], name='id_idx'),
        ),
    ]
