# Generated by Django 4.0 on 2023-10-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0017_rename_product_product_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
