# Generated by Django 4.0 on 2023-10-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0018_marketplace_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.store'),
        ),
    ]
