# Generated by Django 4.0 on 2023-09-27 09:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0018_remove_customuser_uid_idx_rename_uid_customuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
