# Generated by Django 4.0 on 2024-03-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0019_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('validity_period', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.category')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.store')),
            ],
        ),
    ]
