# Generated by Django 4.0 on 2023-09-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0019_alter_customuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=300)),
                ('nuban', models.CharField(max_length=10, unique=True)),
                ('bank_code', models.IntegerField()),
                ('user', models.OneToOneField(limit_choices_to={'is_store_owner': True}, on_delete=django.db.models.deletion.CASCADE, to='mall.customuser')),
            ],
        ),
    ]
