# Generated by Django 4.0 on 2023-10-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0019_price_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='profit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
