# Generated by Django 4.0 on 2023-10-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0020_price_profit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='profit_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='store',
        ),
    ]
