# Generated by Django 4.0 on 2023-09-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0021_wallet_product_upload_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.category'),
        ),
    ]
