# Generated by Django 4.0 on 2023-10-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0021_remove_price_profit_price_remove_price_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplace',
            name='profit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
