# Generated by Django 4.0 on 2024-03-19 07:15

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0022_buyerbehaviour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='TIN_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='cover_image',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='theme',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
