# Generated by Django 4.0 on 2023-09-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0022_alter_store_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreDomainPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.CharField(editable=False, max_length=10)),
                ('one_time_payment_status', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(max_length=30, unique=True)),
                ('user', models.OneToOneField(limit_choices_to={'is_store_owner': True}, on_delete=django.db.models.deletion.CASCADE, to='mall.customuser')),
            ],
        ),
    ]
