# Generated by Django 4.0 on 2023-10-02 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0023_storedomainpaymentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreActivationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_domain_name', models.CharField(max_length=20, unique=True)),
                ('amount_paid', models.CharField(editable=False, max_length=10)),
                ('status', models.CharField(choices=[('ACTIVATED', 'ACTIVATED'), ('DISACTIVATED', 'DISACTIVATED'), ('UNPROCESSED', 'UNPROCESSED'), ('UNDER-REVIEW', 'UNDER-REVIEW')], default='UNPROCESSED', max_length=12)),
                ('payment_status', models.CharField(choices=[('PD', 'Paid'), ('UP', 'Unpaid')], default='UP', max_length=6)),
                ('payment_reference', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='domain_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_url',
        ),
        migrations.DeleteModel(
            name='StoreDomainPaymentInfo',
        ),
        migrations.AddField(
            model_name='storeactivationinfo',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mall.store'),
        ),
        migrations.AddField(
            model_name='storeactivationinfo',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_store_owner': True}, on_delete=django.db.models.deletion.CASCADE, to='mall.customuser'),
        ),
    ]
