# Generated by Django 4.0 on 2024-03-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0023_alter_store_tin_number_alter_store_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerbehaviour',
            name='answer',
            field=models.IntegerField(null=True),
        ),
    ]
