# Generated by Django 4.0 on 2023-10-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0023_remove_marketplace_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='profit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='price',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.store'),
        ),
    ]
