# Generated by Django 4.0 on 2023-10-03 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0024_storeactivationinfo_remove_store_domain_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['id'], name='store_id_idx'),
        ),
    ]
