# Generated by Django 4.0 on 2024-03-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0024_alter_buyerbehaviour_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerbehaviour',
            name='question',
            field=models.CharField(default='How satisfied are you with our services ?', max_length=200, unique=True),
        ),
    ]
