# Generated by Django 4.0 on 2023-10-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0025_price_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='profit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
