# Generated by Django 4.0 on 2023-10-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0026_size_remove_brand_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sn',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
