# Generated by Django 4.0 on 2023-10-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0026_alter_price_profit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='profit_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='store',
        ),
        migrations.RemoveField(
            model_name='price',
            name='updated_at',
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['size'], name='size_size_sizex'),
        ),
        migrations.AddField(
            model_name='storeprofit',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.store'),
        ),
    ]
