# Generated by Django 4.0 on 2024-03-19 17:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0027_store_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Grey', 'Grey'), ('Black', 'Black'), ('White', 'White'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Lime', 'Lime'), ('Teal', 'Teal'), ('Indigo', 'Indigo'), ('Maroon', 'Maroon'), ('Olive', 'Olive'), ('Navy', 'Navy'), ('Silver', 'Silver')], max_length=20, null=True), size=None),
        ),
    ]
