# Generated by Django 4.0 on 2023-10-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0027_alter_product_sku_alter_product_sn_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sn',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
