# Generated by Django 4.0 on 2023-10-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0029_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(through='mall.Price', to='mall.Size'),
        ),
    ]
