# Generated by Django 4.0 on 2023-10-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0030_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Green', 'Green'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('Black', 'Black'), ('White', 'White'), ('Beige', 'Beige'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Lavender', 'Lavender'), ('Teal', 'Teal'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Maroon', 'Maroon'), ('Turquoise', 'Turquoise'), ('Indigo', 'Indigo'), ('Violet', 'Violet'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Nude', 'Nude'), ('Neutral', 'Neutral'), ('Berge', 'Berge'), ('Ivory', 'Ivory'), ('Metallic', 'Metallic'), ('Grow', 'Grow'), ('Multi', 'Multi'), ('Clear', 'Clear'), ('Burgundy', 'Burgundy'), ('Rose Gold', 'Rose Gold')], max_length=9, null=True),
        ),
    ]
