# Generated by Django 4.0 on 2023-10-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0030_alter_price_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='price',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_prices', to='mall.store'),
        ),
        migrations.AlterField(
            model_name='price',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='mall.product'),
        ),
    ]
