# Generated by Django 4.2 on 2024-04-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0032_productreview_shippingdata_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdata',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
