# Generated by Django 4.0 on 2023-10-25 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0033_alter_price_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofit',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='mall.size'),
        ),
    ]
