# Generated by Django 4.0 on 2023-10-10 15:02

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0033_alter_price_price_alter_price_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='upload_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='mall.ProductImage'),
        ),
    ]
