# Generated by Django 4.2 on 2024-04-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0033_shippingdata_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='background_color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='button_color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='card_elevation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='card_view',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='color_gradient',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='patterns',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
