# Generated by Django 4.0 on 2023-10-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0034_productimage_alter_product_upload_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sn'], name='product_sn_snx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='product_sku_skux'),
        ),
    ]
