# Generated by Django 4.0 on 2023-10-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0035_product_product_sn_snx_product_product_sku_skux'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['name'], name='brand_name_namex'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='category_name_namex'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['price'], name='price_price_pricex'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['image'], name='product_images_imagesx'),
        ),
        migrations.AddIndex(
            model_name='producttypes',
            index=models.Index(fields=['name'], name='producttypes_name_namex'),
        ),
        migrations.AddIndex(
            model_name='size',
            index=models.Index(fields=['name'], name='size_name_namex'),
        ),
        migrations.AddIndex(
            model_name='subcategories',
            index=models.Index(fields=['name'], name='subcategories_name_namex'),
        ),
    ]
