# Generated by Django 4.2 on 2024-05-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0035_alter_store_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completed_steps',
            field=models.IntegerField(default=0),
        ),
    ]
