# Generated by Django 4.0 on 2023-10-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0036_remove_customuser_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shipping_address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
