# Generated by Django 4.2 on 2024-05-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0036_customuser_completed_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='card_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
