# Generated by Django 4.0 on 2023-10-25 14:22

import cloudinary_storage.storage
from django.db import migrations, models
import mall.validator


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0037_customuser_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='TIN_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='year_of_establishment',
            field=models.DateField(null=True, validators=[mall.validator.YearValidator]),
        ),
    ]
