# Generated by Django 4.2 on 2024-05-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0037_store_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
