# Generated by Django 4.0 on 2023-10-26 22:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0038_alter_store_tin_number_alter_store_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, null=True)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('Black', 'Black'), ('White', 'White'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Lime', 'Lime'), ('Teal', 'Teal'), ('Indigo', 'Indigo'), ('Maroon', 'Maroon'), ('Olive', 'Olive'), ('Navy', 'Navy'), ('Silver', 'Silver')], max_length=20), size=None)),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.productvariant')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.store')),
            ],
        ),
        migrations.RemoveField(
            model_name='storeprofit',
            name='product',
        ),
        migrations.RemoveField(
            model_name='storeprofit',
            name='size',
        ),
        migrations.RemoveField(
            model_name='storeprofit',
            name='store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='StoreProfit',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ManyToManyField(to='mall.Product'),
        ),
    ]
