# Generated by Django 4.0 on 2023-10-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0039_productvariant_storeproductvariant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ManyToManyField(blank=True, null=True, to='mall.Store'),
        ),
    ]
