# Generated by Django 4.0 on 2023-10-27 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0040_alter_product_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ManyToManyField(blank=True, to='mall.Store'),
        ),
    ]
