# Generated by Django 4.0 on 2023-10-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0042_remove_product_images_product_images'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productimage',
            name='product_images_imagesx',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='images',
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['images'], name='product_images_imagesx'),
        ),
    ]
