# Generated by Django 4.0 on 2023-10-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0043_remove_productimage_product_images_imagesx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ManyToManyField(related_name='variants', to='mall.Product'),
        ),
    ]
