# Generated by Django 5.1.2 on 2025-01-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0044_alter_customuser_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='bank_code',
            field=models.CharField(null=True),
        ),
    ]
