# Generated by Django 4.0 on 2023-10-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0044_alter_productvariant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ManyToManyField(related_name='product_variants', to='mall.Product'),
        ),
    ]
