# Generated by Django 5.1.2 on 2025-01-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0045_alter_wallet_bank_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.store')),
            ],
        ),
    ]
