# Generated by Django 4.0 on 2023-10-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0045_alter_productvariant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductvariant',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_variants', to='mall.productvariant'),
        ),
    ]
