# Generated by Django 5.1.2 on 2025-01-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0046_productstore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductStore',
        ),
    ]
