# Generated by Django 4.0 on 2023-10-28 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0046_alter_storeproductvariant_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.store'),
        ),
    ]
