# Generated by Django 4.0 on 2023-10-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0047_cart_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ManyToManyField(blank=True, related_name='store_products', to='mall.Store'),
        ),
    ]
