# Generated by Django 5.1.2 on 2025-02-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0047_delete_productstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='has_made_payment',
            field=models.BooleanField(default=False),
        ),
    ]
