# Generated by Django 4.0 on 2023-10-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0048_alter_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='list_product',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
