# Generated by Django 5.2 on 2025-05-26 10:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0049_customuser_is_verified_customuser_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproductpricing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeproductpricing',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_pricings', to='mall.product'),
        ),
        migrations.AlterField(
            model_name='storeproductpricing',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='mall.store'),
        ),
        migrations.AddIndex(
            model_name='storeproductpricing',
            index=models.Index(fields=['store', 'product'], name='mall_storep_store_i_2f7435_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproductpricing',
            index=models.Index(fields=['retail_price'], name='mall_storep_retail__1493d3_idx'),
        ),
    ]
