# Generated by Django 4.0 on 2023-11-13 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0050_product_product_id_idx_product_product_name_namex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='paid',
        ),
        migrations.AddField(
            model_name='wallet',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.customuser'),
        ),
    ]
