# Generated by Django 4.0 on 2023-11-16 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0051_remove_wallet_paid_wallet_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='storeactivationinfo',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storeactivationinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='wallet',
            name='account_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bank_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='nuban',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.store'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner'], name='store_owner_ownerx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name'], name='store_name_namex'),
        ),
        migrations.DeleteModel(
            name='AccountDetails',
        ),
        migrations.DeleteModel(
            name='StoreActivationInfo',
        ),
    ]
