# Generated by Django 5.2 on 2025-07-12 09:19

import cloudinary_storage.storage
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0051_alter_subcategories_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='servicesbusinessinformation',
            name='business_photograph2',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='servicesbusinessinformation',
            name='business_photograph3',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='cover_image',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.FileField(null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=''),
        ),
    ]
