# Generated by Django 5.2 on 2025-07-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0052_alter_customuser_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_token',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
