# Generated by Django 5.2 on 2025-07-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0053_customuser_verification_token_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='email',
        ),
        migrations.AddField(
            model_name='store',
            name='dns_record_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='domain_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
