# Generated by Django 4.0 on 2023-11-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0053_store_facebook_store_instagram_store_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='theme',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
