# Generated by Django 5.2 on 2025-07-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0054_remove_store_email_store_dns_record_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['slug'], name='store_slug_idx'),
        ),
    ]
