# Generated by Django 4.0 on 2023-11-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_remove_orderitems_store_variant'),
        ('mall', '0055_product_sales_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.store'),
        ),
        migrations.DeleteModel(
            name='StoreProductVariant',
        ),
    ]
