# Generated by Django 5.2 on 2025-08-01 14:30

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mall', '0056_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_logistics',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_operations',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_services',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_store_owner',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to=''),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_store_owner'], name='user_store_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_verified'], name='user_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['verification_token'], name='user_token_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplace',
            index=models.Index(fields=['store', 'list_product'], name='marketplace_store_list_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplace',
            index=models.Index(fields=['product', 'list_product'], name='marketplace_product_list_idx'),
        ),
    ]
