# Generated by Django 4.0 on 2023-11-24 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0056_productvariant_retail_price_productvariant_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='retail_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='store',
        ),
        migrations.CreateModel(
            name='StoreProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.productvariant')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.store')),
            ],
        ),
    ]
