# Generated by Django 4.0 on 2023-11-24 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0057_remove_productvariant_retail_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductpricing',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeprices', to='mall.productvariant'),
        ),
    ]
