# Generated by Django 5.2 on 2025-08-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0057_alter_customuser_is_logistics_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeproductpricing',
            unique_together={('store', 'product')},
        ),
        migrations.AddIndex(
            model_name='marketplace',
            index=models.Index(fields=['store', 'product', 'list_product'], name='marketplace_composite_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available'], name='product_cat_avail_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['upload_status', 'is_available'], name='product_status_avail_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sales_count'], name='product_sales_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='product_created_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['completed'], name='store_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['created_at'], name='store_created_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['owner', 'completed'], name='store_owner_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproductpricing',
            index=models.Index(fields=['store', 'retail_price'], name='store_pricing_price_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproductpricing',
            index=models.Index(fields=['created_at'], name='store_pricing_created_idx'),
        ),
    ]
