# Generated by Django 5.2 on 2025-08-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0058_alter_storeproductpricing_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='public_id',
            field=models.CharField(blank=True, help_text='Cloudinary public ID for optimizations', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['public_id'], name='product_images_public_idx'),
        ),
    ]
