# Generated by Django 4.0 on 2023-11-25 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0058_alter_storeproductpricing_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductpricing',
            name='product_variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storeprices', to='mall.productvariant'),
        ),
    ]
