# Generated by Django 5.2 on 2025-08-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0059_productimage_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment', 'Payment Credited'), ('withdrawal', 'Withdrawal'), ('product_added', 'Product Added'), ('order', 'New Order'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
