# Generated by Django 4.0 on 2023-12-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0060_alter_storeproductpricing_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Personal Assistant', 'Personal Assistant'), ('Fashion Designer', 'Fashion Designer'), ('Makeup Artist', 'Makeup Artist')], max_length=18, null=True),
        ),
    ]
