# Generated by Django 5.2 on 2025-08-15 14:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0060_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='mall.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to='mall.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='mall_savedp_user_id_54cb8f_idx'), models.Index(fields=['store', 'created_at'], name='mall_savedp_store_i_5e1c4d_idx'), models.Index(fields=['product'], name='mall_savedp_product_84d39b_idx')],
                'unique_together': {('user', 'product', 'store')},
            },
        ),
    ]
