# Generated by Django 5.2 on 2025-08-18 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mall', '0061_savedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=10)),
                ('resource_type', models.CharField(choices=[('PRODUCT', 'Product'), ('STORE', 'Store'), ('ORDER', 'Order'), ('USER', 'User'), ('SYSTEM', 'System')], max_length=10)),
                ('resource_id', models.CharField(blank=True, max_length=36, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdminCustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('product_view', 'Can view products'), ('product_add', 'Can add products'), ('product_edit', 'Can edit products'), ('product_delete', 'Can delete products'), ('store_view', 'Can view stores'), ('store_edit', 'Can edit stores'), ('store_delete', 'Can delete stores'), ('order_view', 'Can view orders'), ('order_edit', 'Can edit orders'), ('order_delete', 'Can delete orders'), ('user_view', 'Can view users'), ('user_create', 'Can create users'), ('user_edit', 'Can edit users'), ('user_delete', 'Can delete users'), ('analytics_view', 'Can view analytics'), ('system_config', 'Can configure system')], max_length=20)),
                ('granted', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('product_admin', 'Product Admin'), ('store_admin', 'Store Admin'), ('order_admin', 'Order Admin'), ('user_admin', 'User Admin'), ('analytics_admin', 'Analytics Admin')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('product_admin', 'Product Admin'), ('store_admin', 'Store Admin'), ('order_admin', 'Order Admin'), ('user_admin', 'User Admin'), ('analytics_admin', 'Analytics Admin')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active_admin',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['admin_role'], name='user_role_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active_admin'], name='user_active_admin_idx'),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admincustompermission',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admincustompermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminuserrole',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminuserrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['admin_user', '-timestamp'], name='mall_admina_admin_u_7df210_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='mall_admina_action_e348a7_idx'),
        ),
        migrations.AddIndex(
            model_name='adminauditlog',
            index=models.Index(fields=['resource_type', '-timestamp'], name='mall_admina_resourc_8bb6f8_idx'),
        ),
        migrations.AddIndex(
            model_name='admincustompermission',
            index=models.Index(fields=['user', 'granted'], name='mall_adminc_user_id_68dfba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='admincustompermission',
            unique_together={('user', 'permission')},
        ),
        migrations.AddIndex(
            model_name='adminuserrole',
            index=models.Index(fields=['user'], name='mall_adminu_user_id_7d3b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuserrole',
            index=models.Index(fields=['role'], name='mall_adminu_role_47d40e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adminuserrole',
            unique_together={('user', 'role')},
        ),
    ]
