# Generated by Django 5.2 on 2026-02-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0063_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuserrole',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('product_admin', 'Product Admin'), ('product_manager', 'Product Manager'), ('store_admin', 'Store Admin'), ('order_admin', 'Order Admin'), ('user_admin', 'User Admin'), ('analytics_admin', 'Analytics Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('product_admin', 'Product Admin'), ('product_manager', 'Product Manager'), ('store_admin', 'Store Admin'), ('order_admin', 'Order Admin'), ('user_admin', 'User Admin'), ('analytics_admin', 'Analytics Admin')], db_index=True, max_length=20, null=True),
        ),
    ]
