# Generated by Django 4.0 on 2023-12-07 15:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('In-Review', 'In-Review')], default='Pending', max_length=9, null=True)),
                ('order_id', models.CharField(max_length=5, null=True, unique=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to='mall.store')),
            ],
        ),
    ]
