# Generated by Django 4.0 on 2023-09-27 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0021_wallet_product_upload_status'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(limit_choices_to={'is_consumer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mall.customuser'),
        ),
    ]
