# Generated by Django 4.0 on 2024-01-18 21:53

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cartitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeliveryConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='order.storeorder')),
            ],
        ),
    ]
