# Generated by Django 4.0 on 2023-09-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
