# Generated by Django 4.0 on 2024-01-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderdeliveryconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('In-Review', 'In-Review'), ('Delivered', 'Delivered')], default='Pending', max_length=9, null=True),
        ),
    ]
