# Generated by Django 4.0 on 2023-11-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0049_alter_marketplace_list_product'),
        ('order', '0005_orderitems_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='product',
            field=models.ManyToManyField(related_name='order_products', to='mall.Product'),
        ),
    ]
