# Generated by Django 4.0 on 2024-01-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_storeorder_delivery_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeorder',
            old_name='order_id',
            new_name='order_sn',
        ),
    ]
