# Generated by Django 4.0 on 2024-01-19 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_order_id_storeorder_order_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliveryconfirmation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.storeorder'),
        ),
    ]
