# Generated by Django 4.0 on 2023-11-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orderitems_product_orderitems_product'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['id'], name='order_id_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer'], name='order_buyer_buyerx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store'], name='order_store_storex'),
        ),
    ]
