# Generated by Django 4.0 on 2024-01-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderdeliveryconfirmation_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdeliveryconfirmation',
            old_name='order',
            new_name='storeorder',
        ),
    ]
