# Generated by Django 4.0 on 2024-01-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_order_orderdeliveryconfirmation_storeorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdeliveryconfirmation',
            old_name='storeorder',
            new_name='userorder',
        ),
    ]
