# Generated by Django 4.0 on 2024-02-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_state_delete_address_storeorder_delivery_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=11),
        ),
    ]
