# Generated by Django 4.0 on 2024-03-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_paymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('nmpleted', 'Completed'), ('Enroute', 'Enroute'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Pending', max_length=9, null=True),
        ),
    ]
