# Generated by Django 5.1.2 on 2024-11-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_storeorder_status_paystackwebhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='tracking_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='tracking_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
