# Generated by Django 4.0 on 2023-11-09 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0050_product_product_id_idx_product_product_name_namex_and_more'),
        ('order', '0020_alter_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.productvariant'),
        ),
    ]
