# Generated by Django 5.1.2 on 2025-02-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_paystackwebhook_order_storeorder_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystackwebhook',
            name='purpose',
            field=models.CharField(default='order', max_length=50),
        ),
    ]
