# Generated by Django 5.2 on 2025-06-04 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0051_alter_subcategories_unique_together_and_more'),
        ('order', '0021_paystackwebhook_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['status'], name='order_store_status_4f73b6_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['store', 'status'], name='order_store_store_i_4956e7_idx'),
        ),
        migrations.AddIndex(
            model_name='storeorder',
            index=models.Index(fields=['total_price'], name='order_store_total_p_df66c5_idx'),
        ),
    ]
