# Generated by Django 4.0 on 2023-11-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0050_product_product_id_idx_product_product_name_namex_and_more'),
        ('order', '0021_order_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.productvariant'),
        ),
    ]
