# Generated by Django 5.2 on 2025-08-15 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0060_notification_notification_type'),
        ('order', '0022_storeorder_order_store_status_4f73b6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recipient_code', models.CharField(max_length=100)),
                ('transfer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('paystack_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='mall.store')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_records', to='mall.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'status'], name='order_withd_store_i_8f7a4b_idx'), models.Index(fields=['created_at'], name='order_withd_created_cd4cd3_idx'), models.Index(fields=['amount'], name='order_withd_amount_7f9b03_idx')],
            },
        ),
    ]
