# Generated by Django 4.0 on 2023-11-10 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0050_product_product_id_idx_product_product_name_namex_and_more'),
        ('order', '0022_remove_order_product_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='store_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to='mall.storeproductvariant'),
        ),
    ]
