# Generated by Django 4.0 on 2023-11-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_orderitems_store_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='store_variant',
        ),
    ]
