# Generated by Django 5.2.11 on 2026-03-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_withdrawalrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
