# Generated by Django 4.0 on 2023-12-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0061_customuser_is_services_customuser_type'),
        ('order', '0024_remove_orderitems_store_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mall.productvariant'),
        ),
    ]
