# Generated by Django 4.0 on 2023-12-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0061_customuser_is_services_customuser_type'),
        ('order', '0025_cartitem_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores_cart', to='mall.store'),
        ),
    ]
