# Generated by Django 4.0 on 2023-12-02 22:15

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=14)),
                ('date_of_birth', models.DateField()),
                ('profile_image', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage, upload_to='')),
                ('password', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('Personal Assistant', 'Personal Assistant'), ('Fashion Designer', 'Fashion Designer'), ('Makeup Artist', 'Makeup Artist')], max_length=18)),
            ],
        ),
    ]
