# Generated by Django 4.0 on 2023-12-02 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
