name: Django Production Deployment

on:
  push:
    branches: [ master ]

env:
  DJANGO_SETTINGS_MODULE: setup.settings
  PYTHON_VERSION: '3.12'
  CI: 'true'
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CLOUDINARY_NAME: dummy
      CLOUDINARY_API_KEY: dummy
      CLOUDINARY_SECRET: dummy
      CLOUDINARY_URL: cloudinary://dummy:dummy@dummy
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r main/requirements.txt
        
    - name: Run tests
      run: |
        python main/manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r main/requirements.txt
        
    - name: Collect static files
      run: python main/manage.py collectstatic --noinput
      
    - name: Deploy to Production
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/django-app/prod
          git reset --hard HEAD
          git pull origin master
          source venv/bin/activate
          pip install -r main/requirements.txt
          python main/manage.py makemigrations
          python main/manage.py migrate
          sudo systemctl restart gunicorn-rocktea-prod
          sudo systemctl restart celery-worker-rocktea-prod.service
          sudo systemctl restart nginx