name: Staging Test & Deploy

on:
  push:
    branches: [ test ]

jobs:
  test:
    name: Run Tests on GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 2
    
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 3s
          --health-retries 3
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        
    - name: Install dependencies
      run: |
        pip install django psycopg2-binary tblib asgiref sqlparse
        
    - name: Run Django Tests
      env:
        CI: 'true'
        DJANGO_SETTINGS_MODULE: setup.test_settings
        PGHOST: localhost
        PGPORT: 5432
        PGDATABASE: test_db
        PGUSER: postgres
        PGPASSWORD: postgres
      run: |
        cd main
        python manage.py test mall.tests.test_models.ProductModelTest.test_create_product --verbosity=0
        
  deploy:
    name: Deploy to Server
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Deploy to Staging Server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/django-app/dev
          git pull origin test
          source venv/bin/activate
          pip install --no-deps -r main/requirements.txt
          python main/manage.py migrate --run-syncdb
          sudo systemctl reload gunicorn-rocktea
          sudo systemctl restart celery-worker-rocktea.service
          sudo systemctl restart celery-beat-rocktea.service
          sudo systemctl restart flower-dev.service